version: '3.1'

services:

  server:
    container_name: bank-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "3306:3306"
    depends_on:
      - db